version: 0.2

env:
    variables:
        CDK_LOCATION: CLOUD

batch:
    fail-fast: false
    build-graph:
        - identifier: MedsTrackerAPIServiceBuildOutputArtifact
          ignore-failure: false
          buildspec: services/API/buildspec.yml
        - identifier: MedsTrackerAuthServiceBuildOutputArtifact
          ignore-failure: false
          buildspec: services/auth/buildspec.yml
        - identifier: MedsTrackerBackendStackBuildOutputArtifact
          ignore-failure: false
          buildspec: ./
          depend-on:
              - MedsTrackerAuthServiceBuildOutputArtifact
              - MedsTrackerAPIServiceBuildOutputArtifact

phases:
    pre_build:
        commands:
            - "ls"
            - "cd services/API"
            - "ls"

artifacts:
    name: "MedsTrackerBackendStackBuildOutputArtifact"
    files:
        - "**/dist/**/*"
        - "cloudformation/template.json"
