version: 0.2

env:
    variables:
        CDK_LOCATION: CLOUD

batch:
    fail-fast: false
    build-list:
        - identifier: API
          ignore-failure: false
          buildspec: "services/API/buildspec.yml"
        - identifier: auth
          ignore-failure: false
          buildspec: "services/auth/buildspec.yml"

phases:
    pre_build:
        commands:
            - "ls"
            - "cd services/API"
            - "ls"

artifacts:
    name: "MedsTrackerBackendStackBuildOutputArtifact"
    files:
        - "**/dist/**/*"
        - "cloudformation/template.json"
