service: meds-tracker-api-offline
useDotenv: true

custom:
    serverless-offline:
        httpPort: 3010

plugins:
    - serverless-offline

provider:
    name: aws
    region: eu-west-1
    runtime: nodejs14.x

functions:
    main:
        handler: dist/ncc/index.handler
        events:
            - httpApi:
                  method: ANY
                  path: /
            - httpApi:
                  method: ANY
                  path: "{proxy+}"
